---
- name: blog_app group is present
  group: name=blog_app state=present
  
- name: blog_app user is present
  user: name=blog_app group=blog_app shell=/usr/sbin/nologin state=present
  
- name: component home is present and has correct permissions
  file: path={{ blog_component_home }} state=directory owner=blog_app group=blog_app

- name: django is installed in the virtualenv
  pip: name=django version=1.8.4 virtualenv={{ blog_component_home}}/venv
  become: yes
  become_user: blog_app
  become_method: sudo

- name: Make sure ssh keys are present
  shell: ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ''
  args:
      creates: /etc/ssh/ssh_host_ed25519_key
